baseURL = "https://nkdews.me/"
title = "Nirmals Personal Blog - Fullstack Developer and Cloud Solution Architect."
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[permalinks]
posts = "/:title"

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1



[[languages.en.menu.main]]
name = "archives"
url = "archives"
weight = 5



[[languages.en.menu.main]]
name = "timeline"
url = "categories/timeline/"
weight = 6

[[languages.en.menu.main]]
name = "search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "categories"
url = "categories/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = false
images = [ "papermod-cover.png" ]

  [params.label]
  text = "NKDews"
  icon = "/site-logo.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"
  imageWidth = 120
  imageHeight = 120

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Documenting Every Thought.."
  Content = """
Welcome to my Personal Blog. I am a fulltime freelancer working on Cloud Based Projects
- I write on various subject which interest Me. 
"""

  [[params.socialIcons]]
  name = "twitter"
  url = "https://github.com/nirmal_kumar"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nk-gears"

  [[params.socialIcons]]
  name = "KoFi"
  url = "https://ko-fi.com/nirmal_kumar"

  [[params.socialIcons]]
  name = "RsS"
  url = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
